[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[secrets_scan]
  omit_keys = [
    "VITE_API_URL",
    "VITE_CLOUDINARY_CLOUD_NAME",
    "VITE_CLOUDINARY_UPLOAD_PRESET"
  ]
